import { readFile } from "node:fs/promises";
import path from "node:path";
import { loadEnv } from "../config/env";
import { canonicalizeGalleryTerm, normalizeGalleryKeywordsToEnglish } from "../utils/gallery-language";
import { buildAutoGeneratedMetadata, type GalleryImageMetadata } from "../utils/gallery-metadata";

const SUPPORTED_IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

type VisionChatMessage = {
  role: "system" | "user";
  content:
    | string
    | Array<
        | { type: "text"; text: string }
        | { type: "image_url"; image_url: { url: string; detail?: "low" | "high" | "auto" } }
      >;
};

type VisionChatResponse = {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

const SYSTEM_PROMPT = `You are LootCardChoose's gallery metadata analyzer.
Analyze a collectible card image and produce metadata for Discord users to search the gallery.
Return one strict JSON object only.
Do not return markdown.
Do not return code fences.
Do not explain anything.`;

const USER_PROMPT = `Analyze this trading card image and return strict JSON only.

The JSON must match this schema exactly:
{
  "title": string,
  "description": string,
  "tags": string[],
  "style": string,
  "rarity": "N" | "R" | "SR" | "SSR" | "UR",
  "category": string,
  "character": string,
  "color": string,
  "mood": string,
  "scene": string,
  "price": number,
  "metadata": {
    "source": "vision-ai",
    "visionProvider": "siliconflow",
    "visionModel": string,
    "confidence": number,
    "zh"?: {
      "title"?: string,
      "description"?: string,
      "tags"?: string[]
    }
  }
}

Rules:
- Title must be a natural English product title based on the image content, never a filename or UUID.
- Description must be a short English product description suitable for gallery search and product display.
- Tags must be primarily English searchable keywords.
- Main searchable fields must be in English: title, description, tags, style, category, character, color, mood, scene.
- If Chinese hints are helpful, place them under metadata.zh instead of the main search fields.
- style should be an English phrase such as "black gold anime", "cyberpunk mecha", or "dark fantasy".
- category should be a concise English label such as "anime", "mecha", "fantasy", "game", "cute", or "other".
- character should be an English label such as "female character", "male character", "robot", "monster", "animal", "object", or "unknown".
- color, mood, and scene should also be short English phrases.
- Include terms like "black gold", "female character", "anime", and "collectible card" when relevant.
- Prefer image content over assumptions from filenames.
- Return JSON only.`;

const UUIDISH_TITLE_PATTERN = /^[0-9a-f]{8}(?:[\s-][0-9a-f]{4}){3}[\s-][0-9a-f]{12}$/i;
const SUPPORTED_RARITIES = new Set(["N", "R", "SR", "SSR", "UR"]);
const FALLBACK_VISION_MODELS = ["Qwen/Qwen3-VL-8B-Instruct"];

const sanitizeJsonString = (value: string): string =>
  value.trim().replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```$/i, "");

const normalizeRequiredString = (value: unknown, field: string): string => {
  if (typeof value !== "string") {
    throw new Error(`Vision JSON field "${field}" must be a string`);
  }
  const normalized = value.trim();
  if (normalized.length === 0) {
    throw new Error(`Vision JSON field "${field}" must not be empty`);
  }
  return normalized;
};

const normalizeTags = (value: unknown): string[] => {
  if (!Array.isArray(value)) {
    throw new Error('Vision JSON field "tags" must be a string array');
  }

  const tags = value
    .filter((tag): tag is string => typeof tag === "string")
    .map((tag) => tag.trim())
    .filter((tag) => tag.length > 0);

  if (tags.length === 0) {
    throw new Error('Vision JSON field "tags" must not be empty');
  }

  return normalizeGalleryKeywordsToEnglish(tags);
};

const parseJsonResponse = (content: string, imagePath: string, model: string): GalleryImageMetadata => {
  const parsed = JSON.parse(sanitizeJsonString(content)) as Record<string, unknown>;
  const title = normalizeRequiredString(parsed.title, "title");
  const description = normalizeRequiredString(parsed.description, "description");
  const style = canonicalizeGalleryTerm(normalizeRequiredString(parsed.style, "style"));
  const rarity = normalizeRequiredString(parsed.rarity, "rarity").toUpperCase();
  const category = canonicalizeGalleryTerm(normalizeRequiredString(parsed.category, "category"));
  const character = canonicalizeGalleryTerm(normalizeRequiredString(parsed.character, "character"));
  const color = canonicalizeGalleryTerm(normalizeRequiredString(parsed.color, "color"));
  const mood = canonicalizeGalleryTerm(normalizeRequiredString(parsed.mood, "mood"));
  const scene = canonicalizeGalleryTerm(normalizeRequiredString(parsed.scene, "scene"));
  const tags = normalizeTags(parsed.tags);
  const metadata = parsed.metadata;

  if (
    UUIDISH_TITLE_PATTERN.test(title) ||
    title.toLowerCase() === path.basename(imagePath, path.extname(imagePath)).toLowerCase()
  ) {
    throw new Error("Vision title looks like a filename fallback");
  }
  if (!SUPPORTED_RARITIES.has(rarity)) {
    throw new Error(`Vision JSON field "rarity" must be one of ${Array.from(SUPPORTED_RARITIES).join(", ")}`);
  }
  if (typeof parsed.price !== "number" || Number.isNaN(parsed.price)) {
    throw new Error('Vision JSON field "price" must be a number');
  }
  if (typeof metadata !== "object" || metadata == null || Array.isArray(metadata)) {
    throw new Error('Vision JSON field "metadata" must be an object');
  }

  const typedMetadata = metadata as Record<string, unknown>;
  const confidence = typedMetadata.confidence;
  if (typeof confidence !== "number" || Number.isNaN(confidence)) {
    throw new Error('Vision JSON metadata.confidence must be a number');
  }

  return {
    title,
    description,
    tags,
    style,
    rarity,
    category,
    character,
    color,
    mood,
    scene,
    price: parsed.price,
    isActive: true,
    metadata: {
      ...typedMetadata,
      source: "vision-ai",
      visionProvider: "siliconflow",
      visionModel: model,
      confidence,
    },
  };
};

const getResponseContent = (response: VisionChatResponse): string => {
  const content = response.choices?.[0]?.message?.content;
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content
      .map((item) => (typeof item.text === "string" ? item.text : ""))
      .join("")
      .trim();
  }
  throw new Error("Empty vision response");
};

const extractShortErrorMessage = async (response: Response): Promise<string> => {
  try {
    const payload = (await response.json()) as { message?: string; error?: { message?: string } };
    return payload.error?.message?.slice(0, 200) || payload.message?.slice(0, 200) || response.statusText;
  } catch {
    return response.statusText;
  }
};

const ensureSupportedImage = (imagePath: string): void => {
  const extension = path.extname(imagePath).toLowerCase();
  if (!SUPPORTED_IMAGE_EXTENSIONS.has(extension)) {
    throw new Error(`Unsupported image type: ${extension || "unknown"}`);
  }
};

const imageToDataUrl = async (imagePath: string): Promise<string> => {
  ensureSupportedImage(imagePath);
  const extension = path.extname(imagePath).toLowerCase();
  const mimeType = extension === ".jpg" ? "image/jpeg" : `image/${extension.slice(1)}`;
  const buffer = await readFile(imagePath);
  return `data:${mimeType};base64,${buffer.toString("base64")}`;
};

const buildFallbackMetadata = (imagePath: string, syncSourceId?: string): GalleryImageMetadata => ({
  ...buildAutoGeneratedMetadata(path.basename(imagePath), syncSourceId),
  metadata: {
    source: "filename-fallback",
    filename: path.basename(imagePath),
    ...(syncSourceId ? { syncSourceId } : {}),
  },
});

class GalleryVisionMetadataService {
  async analyzeImage(imagePath: string, syncSourceId?: string): Promise<GalleryImageMetadata> {
    const env = loadEnv();
    if (!env.siliconflowApiKey) {
      throw new Error("SILICONFLOW_API_KEY is missing");
    }

    const imageDataUrl = await imageToDataUrl(imagePath);
    const url = `${env.siliconflowBaseUrl.replace(/\/$/, "")}/chat/completions`;
    const modelsToTry = [
      env.siliconflowVisionModel,
      ...FALLBACK_VISION_MODELS.filter((model) => model !== env.siliconflowVisionModel),
    ];
    let lastError: Error | null = null;

    for (const model of modelsToTry) {
      console.log(`[GALLERY VISION] request model=${model}`);
      const messages: VisionChatMessage[] = [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: [
            { type: "image_url", image_url: { url: imageDataUrl, detail: "low" } },
            { type: "text", text: USER_PROMPT },
          ],
        },
      ];

      const response = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${env.siliconflowApiKey}`,
        },
        body: JSON.stringify({
          model,
          messages,
          temperature: 0.2,
        }),
      });

      if (!response.ok) {
        const shortError = await extractShortErrorMessage(response);
        lastError = new Error(`SiliconFlow API failed status=${response.status} error=${shortError}`);

        const shouldRetryModel =
          (response.status === 400 && /model does not exist/i.test(shortError)) ||
          (response.status === 403 && /model disabled/i.test(shortError));

        if (shouldRetryModel && model !== modelsToTry[modelsToTry.length - 1]) {
          console.error(
            `[GALLERY VISION] model unavailable model=${model} status=${response.status} error=${shortError}`
          );
          continue;
        }

        throw lastError;
      }

      const payload = (await response.json()) as VisionChatResponse;
      const metadata = parseJsonResponse(getResponseContent(payload), imagePath, model);
      metadata.metadata = {
        ...(metadata.metadata ?? {}),
        filename: path.basename(imagePath),
        ...(syncSourceId ? { syncSourceId } : {}),
      };
      console.log(`[GALLERY VISION] success title=${metadata.title}`);
      return metadata;
    }

    throw lastError ?? new Error("SiliconFlow API request failed");
  }
}

export const galleryVisionMetadataService = new GalleryVisionMetadataService();
export const createFilenameFallbackMetadata = (imagePath: string, syncSourceId?: string): GalleryImageMetadata =>
  buildFallbackMetadata(imagePath, syncSourceId);
