import { readFile } from "node:fs/promises";
import path from "node:path";
import { loadEnv } from "../config/env";
import { buildAutoGeneratedMetadata, type GalleryImageMetadata } from "../utils/gallery-metadata";

const SUPPORTED_IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

type VisionChatMessage = {
  role: "system" | "user";
  content:
    | string
    | Array<
        | { type: "text"; text: string }
        | { type: "image_url"; image_url: { url: string } }
      >;
};

type VisionChatResponse = {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

const SYSTEM_PROMPT =
  "You are a product metadata generator for collectible gallery card images. Return only one strict JSON object. Do not return markdown. Do not return explanations. Do not wrap JSON in code fences.";

const USER_PROMPT = `Analyze this card image and return strict JSON only.
Required schema:
{
  "title": "English product title",
  "description": "中文简短描述",
  "tags": ["中文tag", "english tag"],
  "style": "black gold / cyberpunk / anime / mecha / fantasy / cute / dark / luxury",
  "rarity": "N / R / SR / SSR / UR",
  "category": "anime / mecha / fantasy / game / cute / other",
  "character": "female / male / robot / monster / animal / object / unknown",
  "color": "主色调",
  "mood": "氛围",
  "scene": "场景",
  "price": 49.99,
  "confidence": 0.85,
  "visionSource": "siliconflow"
}

Rules:
- Output JSON only.
- No markdown.
- No explanation text.
- Tags must include both Chinese and English keywords.
- Tags should be useful for search and include rarity/style/character/theme when visible.
- Example tag mix: ["黑金", "black gold", "SSR", "女角色", "female", "anime"]
- Title must be natural English for Discord/shop display, not a UUID.
- Description must be short Chinese product-style text.
- If uncertain, choose the closest visible category and lower confidence.
- Use only these allowed values for style, rarity, category, character.
- visionSource must be exactly "siliconflow".`;

const sanitizeJsonString = (value: string): string => value.trim().replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```$/i, "");

const parseJsonResponse = (content: string): GalleryImageMetadata => {
  const parsed = JSON.parse(sanitizeJsonString(content)) as Record<string, unknown>;
  const tags = Array.isArray(parsed.tags) ? parsed.tags.filter((tag): tag is string => typeof tag === "string") : [];

  return {
    title: typeof parsed.title === "string" ? parsed.title.trim() : "",
    description: typeof parsed.description === "string" ? parsed.description.trim() : null,
    tags,
    style: typeof parsed.style === "string" ? parsed.style.trim() : null,
    rarity: typeof parsed.rarity === "string" ? parsed.rarity.trim() : null,
    category: typeof parsed.category === "string" ? parsed.category.trim() : null,
    character: typeof parsed.character === "string" ? parsed.character.trim() : null,
    color: typeof parsed.color === "string" ? parsed.color.trim() : null,
    mood: typeof parsed.mood === "string" ? parsed.mood.trim() : null,
    scene: typeof parsed.scene === "string" ? parsed.scene.trim() : null,
    price: typeof parsed.price === "number" || typeof parsed.price === "string" ? parsed.price : 49.99,
    confidence: typeof parsed.confidence === "number" ? parsed.confidence : null,
    visionSource: typeof parsed.visionSource === "string" ? parsed.visionSource.trim() : "siliconflow",
    isActive: true,
    metadata: {
      source: "vision-generated",
      mood: typeof parsed.mood === "string" ? parsed.mood.trim() : null,
      scene: typeof parsed.scene === "string" ? parsed.scene.trim() : null,
      confidence: typeof parsed.confidence === "number" ? parsed.confidence : null,
      visionSource: typeof parsed.visionSource === "string" ? parsed.visionSource.trim() : "siliconflow",
    },
  };
};

const getResponseContent = (response: VisionChatResponse): string => {
  const content = response.choices?.[0]?.message?.content;
  if (typeof content === "string") {
    return content;
  }
  if (Array.isArray(content)) {
    return content
      .map((item) => (typeof item.text === "string" ? item.text : ""))
      .join("")
      .trim();
  }
  throw new Error("Empty vision response");
};

const ensureSupportedImage = (imagePath: string): void => {
  const extension = path.extname(imagePath).toLowerCase();
  if (!SUPPORTED_IMAGE_EXTENSIONS.has(extension)) {
    throw new Error(`Unsupported image type: ${extension || "unknown"}`);
  }
};

const imageToDataUrl = async (imagePath: string): Promise<string> => {
  ensureSupportedImage(imagePath);
  const extension = path.extname(imagePath).toLowerCase();
  const mimeType = extension === ".jpg" ? "image/jpeg" : `image/${extension.slice(1)}`;
  const buffer = await readFile(imagePath);
  return `data:${mimeType};base64,${buffer.toString("base64")}`;
};

const buildFallbackMetadata = (imagePath: string, syncSourceId?: string): GalleryImageMetadata =>
  buildAutoGeneratedMetadata(path.basename(imagePath), syncSourceId);

class GalleryVisionMetadataService {
  async analyzeImage(imagePath: string, syncSourceId?: string): Promise<GalleryImageMetadata> {
    const env = loadEnv();
    if (!env.siliconflowApiKey) {
      throw new Error("SILICONFLOW_API_KEY is missing");
    }

    const imageDataUrl = await imageToDataUrl(imagePath);
    const url = `${env.siliconflowBaseUrl.replace(/\/$/, "")}/chat/completions`;
    const messages: VisionChatMessage[] = [
      { role: "system", content: SYSTEM_PROMPT },
      {
        role: "user",
        content: [
          { type: "text", text: USER_PROMPT },
          { type: "image_url", image_url: { url: imageDataUrl } },
        ],
      },
    ];

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.siliconflowApiKey}`,
      },
      body: JSON.stringify({
        model: env.siliconflowVisionModel,
        messages,
        temperature: 0.2,
        response_format: { type: "json_object" },
      }),
    });

    if (!response.ok) {
      let shortError = response.statusText;
      try {
        const payload = (await response.json()) as VisionChatResponse;
        shortError = payload.error?.message?.slice(0, 200) || shortError;
      } catch {
        shortError = response.statusText;
      }
      throw new Error(`SiliconFlow API failed status=${response.status} error=${shortError}`);
    }

    const payload = (await response.json()) as VisionChatResponse;
    const metadata = parseJsonResponse(getResponseContent(payload));
    const fallback = buildFallbackMetadata(imagePath, syncSourceId);

    return {
      ...fallback,
      ...metadata,
      title: metadata.title && metadata.title.length > 0 ? metadata.title : fallback.title,
      description: metadata.description && metadata.description.length > 0 ? metadata.description : fallback.description,
      tags: metadata.tags && metadata.tags.length > 0 ? metadata.tags : fallback.tags,
      metadata: {
        ...(fallback.metadata ?? {}),
        ...(metadata.metadata ?? {}),
        filename: path.basename(imagePath),
        ...(syncSourceId ? { syncSourceId } : {}),
      },
    };
  }
}

export const galleryVisionMetadataService = new GalleryVisionMetadataService();
