import path from "node:path";

export type GalleryImageMetadata = {
  title?: string;
  description?: string | null;
  tags?: string[];
  style?: string | null;
  rarity?: string | null;
  category?: string | null;
  character?: string | null;
  color?: string | null;
  mood?: string | null;
  scene?: string | null;
  price?: string | number | null;
  confidence?: number | null;
  visionSource?: string | null;
  isActive?: boolean;
  metadata?: Record<string, unknown>;
};

export const LOCAL_GALLERY_SOURCE_PREFIX = "local-gallery:";

const COLOR_TOKENS = ["black", "gold", "red", "blue", "purple"];

const toWords = (filename: string): string[] =>
  path
    .basename(filename, path.extname(filename))
    .split(/[-_\s]+/)
    .map((part) => part.trim().toLowerCase())
    .filter((part) => part.length > 0);

const titleCase = (word: string): string => {
  if (word === "ssr" || word === "sr") {
    return word.toUpperCase();
  }
  return word.charAt(0).toUpperCase() + word.slice(1);
};

export const slugToTitle = (filename: string): string => toWords(filename).map(titleCase).join(" ");

export const buildAutoGeneratedMetadata = (filename: string, syncSourceId?: string): GalleryImageMetadata => {
  const words = toWords(filename);
  const title = slugToTitle(filename);
  const tags = [...new Set(words)];
  const colors = COLOR_TOKENS.filter((token) => words.includes(token));

  let rarity = "";
  if (words.includes("ssr")) {
    rarity = "SSR";
  } else if (words.includes("sr")) {
    rarity = "SR";
  }

  let style = "";
  if (words.includes("cyberpunk")) {
    style = "cyberpunk";
  }

  let category = "card";
  if (words.includes("anime")) {
    category = "anime";
  } else if (words.includes("mecha")) {
    category = "mecha card";
  }

  let character = "";
  if (words.includes("girl") || words.includes("female")) {
    character = "female";
  } else if (words.includes("boy") || words.includes("male")) {
    character = "male";
  } else if (words.includes("mecha")) {
    character = "mecha";
  }

  return {
    title,
    description: `Auto generated metadata for ${title}`,
    tags,
    style,
    rarity,
    category,
    character,
    color: colors.join(" "),
    price: "0.00",
    isActive: true,
    metadata: {
      source: "auto-generated",
      filename,
      ...(syncSourceId ? { syncSourceId } : {}),
    },
  };
};
